"""Contract: the "never hand-author a filter chain" prohibition stays in the skill bodies.

`tests/contracts/test_ffmpeg_module_boundary.py` proves no *module* shells out to ffmpeg outside
the three sanctioned ones, and `agent/permissions.py` denies the binaries in Bash. Neither reaches
the third surface: what the skill body TELLS the agent to do. That instruction is the only control
that operates before a tool call is ever attempted, and it is plain prose — one reword deletes it
with every other gate still green.

This is the failure that motivated the whole set (2026-08-18): an agent asked to make a short-form
video never invoked `video-router`, hand-authored an ffmpeg filter chain in Bash, and
reimplemented `gtm_core.captions` in a scratch script. The prohibition it violated was already
written in `video-finish/body_template.md` — nothing machine-checked that it was still there, or
that the agent had been pointed at the router first.

Deliberately asserts on `body_template.md`, never `SKILL.md`: SKILL.md is generated by
`gtm_core.skills.codegen`, so pinning the generated copy would pass while the source rotted.
"""

from __future__ import annotations

from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
SKILLS = REPO / "plugin" / "skills"

FINISH_BODY = SKILLS / "video-finish" / "body_template.md"
ROUTER_BODY = SKILLS / "video-router" / "body_template.md"

#: Substrings that must survive in video-finish's body. Kept deliberately short and lowercase-
#: matched so a legitimate rewrite of the surrounding sentence passes, while deleting the concept
#: fails. Each maps to a real pixel/loudness operation the module owns.
_FINISH_REQUIRED = (
    "gtm_core.video_finish",
    "gtm_core.captions",
    "gtm_core.video_lint",
    "filter chain",
    "drawtext",
)


def _body(path: Path) -> str:
    assert path.exists(), f"missing authored skill body: {path.relative_to(REPO)}"
    return path.read_text(encoding="utf-8").lower()


@pytest.mark.parametrize("needle", _FINISH_REQUIRED)
def test_video_finish_body_keeps_the_prohibition(needle: str):
    assert needle.lower() in _body(FINISH_BODY), (
        f"video-finish/body_template.md no longer mentions {needle!r}. This body is the only "
        "control that runs BEFORE a tool call — if the prohibition is being reworded, keep the "
        "concept and update this contract deliberately."
    )


def test_video_finish_body_forbids_not_merely_describes():
    """The prohibition has to read as a prohibition. 'never' is the load-bearing word — a body
    that only *documents* ffmpeg usage would satisfy a bare substring check."""
    body = _body(FINISH_BODY)
    assert "never" in body, "video-finish body no longer contains a 'never' prohibition"


def test_video_router_is_the_documented_front_door():
    """A 'make a video' request must land on the router, which picks the creator-pack lane.
    Skipping it is how a screen-recording demo got assembled by hand instead of via demo-clips."""
    body = _body(ROUTER_BODY)
    for lane in ("short-form-video", "repurpose-clips", "restyle-shorts", "demo-clips"):
        assert lane in body, f"video-router no longer routes to the {lane} lane"


def test_skill_md_is_generated_not_authored():
    """Guards the assumption this file rests on: if SKILL.md ever stopped being generated, the
    contract above would be pinning the wrong artifact."""
    for skill in ("video-finish", "video-router"):
        assert (SKILLS / skill / "body_template.md").exists(), (
            f"{skill} has no body_template.md — SKILL.md may have become hand-authored, which "
            "would make this contract pin a generated copy instead of the source."
        )
