"""The synthetic corpus for the signal-first goldens (test plan T0.1).

``python tests/fixtures/signal_first/build_corpus.py`` writes ``corpus/`` next to this file. The
generated bytes are COMMITTED, so a golden compares against fixed input rather than against
whatever this script produces on the day. ``tests/regression/test_signal_first_corpus.py`` proves
the two agree.

Deliberately independent of the code under test: it imports neither ``RECORD_COLUMNS`` nor
``MASTER_COLS``, and writes every column name literally, so a change to those constants cannot
quietly rewrite a golden's input. The only repo import is ``gtm_core.fictionalize``, which turns
placeholder seeds (never a real name) into obviously fictional identities.

Layout written under ``corpus/``::

    profiles/sigfirst/...            the fictional tenant's knowledge
    state/sigfirst/...               its state (seeded as content/; the repo ignores a dir named
                                     content/): exports, pool, ledger, captures, sequences
    lists/gen1.csv gen2.csv gen3.csv the three historical pool layouts, one list each
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO))

from gtm_core import fictionalize  # noqa: E402

HERE = Path(__file__).parent
OUT = HERE / "corpus"
PROFILE = "sigfirst"
N = 36
FETCHED_AT = "2026-09-20T00:00:00+00:00"

# Current pool layout (49 columns), written out literally.
G3 = (
    "first,last,email,title,company,company_domain,city,country,segment,tier,score,conf,"
    "email_status,why_now,case_study,src,conf_tier,heat,top_intent_score,intent_topics,cohort,"
    "qualification_path,signal_source_url,signal_observed,signal_evidence,signal_subject,"
    "signal_agent_kind,category_relation,verdict,verdict_reason,signal_column,suppression,"
    "suppression_date,judge_verdict,judge_verdict_reason,judge_calibrated,judge_defect_class,"
    "lane,lane_reason,pool_row_id,account_id,industry,verdict_on,contact_level,premise_evidence,"
    "firmo_source,firmo_on,researched_for_wave,hook_cell"
).split(",")
G1 = G3[:22]
_G2_DROPS = {
    "lane", "lane_reason", "industry", "verdict_on", "contact_level", "premise_evidence",
    "firmo_source", "firmo_on", "researched_for_wave", "hook_cell",
}  # fmt: skip
G2 = [c for c in G3 if c not in _G2_DROPS]

# HubSpot export layouts, current (E-c, 39) and the 2026-07 layout (E-b, 28).
E_B = (
    "First Name,Last Name,Email,Phone Number,Job Title,LinkedIn Bio URL,Company Name,"
    "Company Domain Name,City,Country/Region,Number of Employees,GTM_Segment,GTM_Score,GTM_Tier,"
    "GTM_Persona_Tier,GTM_Why_Now,GTM_Case_Study,GTM_Source,GTM_Run_Date,GTM_Rubric_Version,"
    "GTM_Heat,GTM_Intent_Feeds,GTM_Top_Intent_Score,GTM_Intent_Topics,GTM_Industry,"
    "GTM_Revenue_Range,GTM_New_In_Role,GTM_Qualification_Path"
).split(",")
_EC_TAIL = (
    "conf,GTM_Signal_Source_URL,GTM_Signal_Observed,GTM_Signal_Evidence,GTM_Signal_Subject,"
    "GTM_Signal_Agent_Kind,GTM_Category_Relation,GTM_Verdict,GTM_Verdict_Reason,GTM_Signal_Column"
).split(",")
E_C = E_B[:3] + ["Email Status"] + E_B[3:] + _EC_TAIL

VERDICTS = ["send", "re-angle", "drop", "", "send", "unknownword", "send", "re-angle", "", "send"]
LANES_IN_POOL = ["", "generic", "personalised", "", "repair", "", "hold", "excluded", "", ""]
HEATS = ["0", "1", "2", "3", "", "2", "0", "3", "1", ""]
AGENT_KINDS = ["ai", "human", "none", "unclear", "", "ai", "ai", "human", "", "none"]
TIERS = ["A", "B", "C", "unscored", "A", "B", "C", "A", "B", "C"]
SEGMENTS = ["enterprise", "startup", "unspecified", "enterprise", "enterprise", "startup"]
COUNTRIES = ["singapore", "australia", "singapore", "hong kong", "singapore", "australia"]
INDUSTRIES = ["freight", "logistics", "", "banking", "freight", "insurance"]
TITLES = [
    "Head of AI Platform", "Platform Lead", "Chief Technology Officer", "Head of Security",
    "Director of Engineering", "VP Product", "Software Engineer", "Head of AI Platform",
    "Chief Executive Officer", "Solutions Architect",
]  # fmt: skip
COHORTS = ["wedge-a", "wedge-b", "general", "wedge-a", "general"]
WHY_NOW = [
    "opened a second agent platform team this quarter",
    "raised a new funding round of 40 million to expand",
    "no public announcement found in the last 90 days",
    "verdict: send - strong fit for the wedge",
    "",
    "published an engineering post on routing agents across regions",
    "hired a head of applied AI in the last month",
]
SIGNAL_LEVEL = ["full", "partial", "none", "full", "none", "partial", "full", "none"]
URLS = [f"https://pages.example/notes/{i}" for i in range(6)]
SENTENCES = [
    "The team now runs relay and mesh agents across three regions in production.",
    "A second platform group was formed to own agent routing and audit records.",
    "The company described its agents handing work between two separate firms.",
    "An engineering post explains how each agent action is recorded for review.",
    "The announcement covers a pilot where agents settle invoices between partners.",
    "Leadership said supervised generative models now handle first-line triage.",
]


def _csv(header: list[str], rows: list[dict]) -> bytes:
    buf = io.StringIO(newline="")
    w = csv.writer(buf)  # default dialect: CRLF, as the real writers produce
    w.writerow(header)
    for r in rows:
        w.writerow([r.get(c, "") for c in header])
    return buf.getvalue().encode("utf-8")


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _slug(name: str) -> str:
    return "".join(c if c.isalnum() else "-" for c in name.lower()).strip("-")


def _letters(i: int) -> str:
    """0 -> 'aa', 1 -> 'ab': an alphabetic tag, so a seed stays one word with no digit."""
    return "abcdefghijklmnopqrstuvwxyz"[i // 26 % 26] + "abcdefghijklmnopqrstuvwxyz"[i % 26]


def accounts() -> list[dict]:
    seen: set[str] = set()
    out: list[dict] = []
    for i in range(N):
        company = fictionalize.company(f"Comp{_letters(i)} Holdings")
        while company in seen:
            company += " Group"
        seen.add(company)
        person = fictionalize.person(f"Giv{_letters(i)} Fam{_letters(i)}")
        first, _, last = person.partition(" ")
        last = last.replace(" ", "-")
        slug = _slug(company)
        domain = f"{slug}.example"
        assert " " not in first and " " not in last, (first, last)
        level = SIGNAL_LEVEL[i % len(SIGNAL_LEVEL)]
        url = URLS[i % len(URLS)]
        evidence = SENTENCES[i % len(SENTENCES)]
        row = {
            "first": first, "last": last or "Seed", "email": f"{first}.{last or 'seed'}@{domain}".lower(),
            "title": TITLES[i % len(TITLES)], "company": company, "company_domain": domain,
            "city": "Seedtown", "country": COUNTRIES[i % len(COUNTRIES)],
            "segment": SEGMENTS[i % len(SEGMENTS)], "tier": TIERS[i % len(TIERS)],
            "score": str(3 + (i * 7) % 10), "conf": str(50 + (i * 3) % 50), "email_status": "valid",
            "why_now": WHY_NOW[i % len(WHY_NOW)], "case_study": "", "src": "seed",
            "conf_tier": "high", "heat": HEATS[i % len(HEATS)],
            "top_intent_score": str((i * 11) % 100) if i % 3 == 0 else "",
            "intent_topics": "agents;routing" if i % 3 == 0 else "",
            "cohort": COHORTS[i % len(COHORTS)], "qualification_path": "signal" if i % 4 else "fit",
            "verdict": VERDICTS[i % len(VERDICTS)],
            "verdict_reason": "thin evidence" if VERDICTS[i % len(VERDICTS)] in ("re-angle", "drop") else "",
            "signal_agent_kind": AGENT_KINDS[i % len(AGENT_KINDS)],
            "category_relation": "prospect" if i % 9 else "partner",
            "industry": INDUSTRIES[i % len(INDUSTRIES)],
            "lane": LANES_IN_POOL[i % len(LANES_IN_POOL)],
            "intent_feeds": "feed-a" if i % 3 == 0 else "",
            "new_in_role": "true" if i % 5 == 0 else "",
            "_level": level, "_url": url, "_evidence": evidence, "_slug": slug,
        }  # fmt: skip
        if level in ("full", "partial"):
            row["signal_source_url"] = url
            row["signal_observed"] = f"2026-09-{1 + i % 18:02d}"
            row["signal_subject"] = company
        if level == "full":
            row["signal_evidence"] = evidence
            row["signal_clause"] = evidence.split(" in ")[0].lower()
        out.append(row)
    return out


def _e_row(a: dict, layout: str) -> dict:
    r = {
        "First Name": a["first"], "Last Name": a["last"], "Email": a["email"],
        "Email Status": a["email_status"], "Job Title": a["title"], "Company Name": a["company"],
        "Company Domain Name": a["company_domain"], "City": a["city"], "Country/Region": a["country"],
        "GTM_Segment": a["segment"], "GTM_Score": a["score"], "GTM_Tier": a["tier"],
        "GTM_Persona_Tier": a["cohort"], "GTM_Why_Now": a["why_now"], "GTM_Source": "seed",
        "GTM_Run_Date": "2026-09-19", "GTM_Rubric_Version": "seed-v1", "GTM_Heat": a["heat"],
        "GTM_Intent_Feeds": a["intent_feeds"], "GTM_Top_Intent_Score": a["top_intent_score"],
        "GTM_Intent_Topics": a["intent_topics"], "GTM_Industry": a["industry"],
        "GTM_New_In_Role": a["new_in_role"], "GTM_Qualification_Path": a["qualification_path"],
        "conf": a["conf"], "GTM_Signal_Source_URL": a.get("signal_source_url", ""),
        "GTM_Signal_Observed": a.get("signal_observed", ""),
        "GTM_Signal_Evidence": a.get("signal_evidence", ""),
        "GTM_Signal_Subject": a.get("signal_subject", ""),
        "GTM_Signal_Agent_Kind": a["signal_agent_kind"], "GTM_Category_Relation": a["category_relation"],
        "GTM_Verdict": a["verdict"], "GTM_Verdict_Reason": a["verdict_reason"],
    }  # fmt: skip
    return r


PROFILE_FILES = {
    "PROFILE.md": (
        "# Fixture tenant\n\n```\ncompany:         Sigfirst Labs\nbrand_name:      Sigfirst\n"
        "default_product: relay\nproducts:\n  - { slug: relay, name: Relay, capabilities: [relay] }\n"
        "target_markets: [singapore, australia]\n```\n"
    ),
    "knowledge/role-vocabulary.toml": (
        'default_persona = "ai-platform"\nsegments = ["enterprise", "startup", "unspecified"]\n'
        '[[persona]]\nname = "ai-platform"\ncues = ["head of ai platform", "platform lead"]\n'
        '[[seat]]\nname = "platform"\npersonas = ["ai-platform"]\nstakes = ["outage", "audit"]\n'
    ),
    "knowledge/premise-vocab.toml": (
        'schema = 1\n[premise.relay-premise]\nclaim = "the reader runs more than one system"\n'
        'min_distinct = 2\nterms = ["relay", "mesh"]\nindustry_terms = ["freight"]\n'
        '[premise.seat-premise]\nclaim = "the reader owns the platform"\nattested_by_seat = true\n'
    ),
    "knowledge/claims.toml": (
        '[[claim]]\nid = "relay-claim"\ngroup = "observability"\nstatus = "verified"\n'
        'statement = "The product records each action."\n'
        'source = "knowledge/references/relay-notes.md:1"\n'
    ),
    "knowledge/proof.toml": (
        '[[proof]]\nid = "relay-proof"\nkind = "anchor"\nmarket = "singapore"\n'
        'figure_kind = "none"\nstatement = "A regulator expects one accountable human per agent."\n'
        'source = "knowledge/guidance/relay-regulator.md:1"\nbinding = false\n'
    ),
    "knowledge/angles.toml": (
        '[[angle]]\nid = "enterprise-platform-relay"\nseat = "platform"\npremise = "relay-premise"\n'
        'claim = "relay-claim"\nproof = "relay-proof"\nopener_kind = "account-event"\n'
        'summary = "One record per action."\nstatus = "draft"\nsegments = ["enterprise"]\n'
        '[[angle]]\nid = "public-platform-relay"\nseat = "platform"\npremise = "seat-premise"\n'
        'claim = "relay-claim"\nproof = "relay-proof"\nopener_kind = "public-event"\n'
        'summary = "One record per action, for any platform owner."\nstatus = "draft"\n'
        'segments = ["enterprise", "startup", "unspecified"]\n'
    ),
    "knowledge/references/relay-notes.md": "# Relay notes\n\nEvery action is recorded.\n",
    "knowledge/guidance/relay-regulator.md": "# Regulator\n\nOne accountable human per agent.\n",
    "knowledge/competitors.toml": (
        '[[competitor]]\nname = "Rivalworks"\ntier = "direct"\naliases = ["Rival Works"]\n'
        'domains = ["rivalworks.example"]\nnote = "fixture competitor"\n'
    ),
    "knowledge/lane-policy.toml": (
        '[auto]\ntrigger = "generic"\n[hold]\nregulated_domains = ["regulated.example"]\n'
        'regulated_industries = ["banking"]\nengaged_statuses = ["engaged"]\n'
    ),
}


def build(out: Path = OUT) -> dict[str, bytes]:
    """Every corpus file as ``{relative path: bytes}``; ``write`` puts them on disk."""
    # `* text=auto eol=lf` at the repo root would rewrite the CSVs' CRLF on commit; the corpus must
    # be byte-exact, like the real writers' output.
    files: dict[str, bytes] = {".gitattributes": b"* -text\n"}
    for rel, text in PROFILE_FILES.items():
        files[f"profiles/{PROFILE}/{rel}"] = text.encode()

    rows = accounts()
    c = f"state/{PROFILE}"
    p = f"{c}/prospects"

    files[f"{p}/prospects-seed-a-hubspot.csv"] = _csv(E_C, [_e_row(a, "c") for a in rows[:16]])
    files[f"{p}/prospects-seed-b-hubspot.csv"] = _csv(E_B, [_e_row(a, "b") for a in rows[16:26]])

    pool = [{**a, "pool_row_id": f"r-{i:010d}"} for i, a in enumerate(rows[24:], start=24)]
    files[f"{p}/sequences/.pool/master-list.csv"] = _csv(G2, pool)
    files[f"{p}/sequences/.pool/suppression.csv"] = _csv(
        ["email", "name", "company_domain", "reason", "date", "note"],
        [
            {"email": rows[3]["email"], "name": "", "company_domain": rows[3]["company_domain"],
             "reason": "unsubscribed", "date": "2026-09-01", "note": "fixture"},
            {"email": rows[30]["email"], "name": "", "company_domain": rows[30]["company_domain"],
             "reason": "bounced", "date": "2026-09-02", "note": "fixture"},
        ],
    )  # fmt: skip
    items = [
        {
            "account_id": f"a-{i:06d}", "id": f"a-{i:06d}", "company": a["company"],
            "domain": a["company_domain"], "status": "active" if i % 11 else "engaged",
            "segment": a["segment"], "tier": a["tier"], "score": a["score"],
            "industry": a["industry"],
        }
        for i, a in enumerate(rows)
    ]  # fmt: skip
    files[f"{p}/latest.json"] = (
        json.dumps({"schema": 1, "items": items}, indent=2, sort_keys=True) + "\n"
    ).encode()
    files[f"{c}/history.jsonl"] = (
        json.dumps(
            {"event": "optout_detected", "email": rows[5]["email"], "ts": "2026-09-10T00:00:00Z"}
        )
        + "\n"
    ).encode()

    # Captures: one per URL with a fixed fetched_at, written chronologically.
    sources = f"{c}/sources"
    index = []
    for url, sentence in zip(URLS, SENTENCES, strict=True):
        text = f"# Notes\n\n{sentence}\n\nMore context follows on the next line.\n"
        sha = _sha(text)
        files[f"{sources}/{sha}.txt"] = text.encode()
        norm = url.rstrip("/").lower()
        index.append(
            json.dumps({"url_norm": norm, "fetched_at": FETCHED_AT, "sha256": sha, "tool": "seed"})
        )
    files[f"{sources}/index.jsonl"] = ("\n".join(index) + "\n").encode()

    for a in rows[:20]:
        files[f"{c}/accounts/{a['_slug']}/account-dossier-2026-09-01.md"] = (
            f"# Dossier: {a['company']}\n\nFixture dossier.\n".encode()
        )

    # Sequences: one enrolled file per lane, registered in cells.toml.
    seq = f"{p}/sequences"
    enrolled_cols = ["email", "Email", "first", "First Name", "last", "Last Name", "company",
                     "Company", "cell_id", "segment", "seat", "title"]  # fmt: skip
    cells = []
    for k, lane in enumerate(["personalised", "generic", "repair", "hold", "excluded"]):
        members = rows[k * 3 : k * 3 + 3]
        cols = (
            enrolled_cols
            + (["why_now", "Why Now"] if lane == "personalised" else [])
            + ["country", "signal_clause", "suppression"]
        )
        data = [
            {"email": m["email"], "Email": m["email"], "first": m["first"], "First Name": m["first"],
             "last": m["last"], "Last Name": m["last"], "company": m["company"],
             "Company": m["company"], "cell_id": f"cell-{lane}", "segment": m["segment"],
             "seat": "platform", "title": m["title"], "why_now": m["why_now"], "Why Now": m["why_now"],
             "country": m["country"], "signal_clause": m.get("signal_clause", ""),
             "suppression": "unsubscribed" if m["email"] == rows[3]["email"] else ""}
            for m in members
        ]  # fmt: skip
        files[f"{seq}/SEQ-{lane}-enrolled.csv"] = _csv(cols, data)
        files[f"{seq}/SEQ-{lane}.md"] = f"# spec {lane}\n\nSign-off: Sam\n".encode()
        cells.append(
            f'[[sequence]]\nid = "SEQ-{lane}"\ncsv = "SEQ-{lane}-enrolled.csv"\n'
            f'spec = "SEQ-{lane}.md"\nlane = "{lane}"\ntitle = "{lane} fixture"\n'
        )
    files[f"{seq}/cells.toml"] = ("\n".join(cells)).encode()

    # The three historical pool layouts, one list each, for the integrity audit. Rows 14-25 mix
    # accounts with and without a dossier. gen3 has four variants because the audit refuses a list
    # whose own lane column disagrees with --lane: blank, routed-generic, routed-personalised, mixed.
    def sample(lane_of) -> list[dict]:
        return [
            {**a, "pool_row_id": f"r-{i:010d}", "lane": lane_of(i, a)}
            for i, a in enumerate(rows[14:26], start=14)
        ]

    files["lists/gen1.csv"] = _csv(G1, sample(lambda i, a: ""))
    files["lists/gen2.csv"] = _csv(G2, sample(lambda i, a: ""))
    files["lists/gen3.csv"] = _csv(G3, sample(lambda i, a: ""))
    files["lists/gen3-generic.csv"] = _csv(G3, sample(lambda i, a: "generic"))
    files["lists/gen3-personalised.csv"] = _csv(G3, sample(lambda i, a: "personalised"))
    files["lists/gen3-mixed.csv"] = _csv(G3, sample(lambda i, a: LANES_IN_POOL[i % 5] or "generic"))

    # Inputs for the render lint, groundedness, score_prospects and the export.
    lint_cols = ["first", "last", "email", "company", "company_domain", "title", "city", "country",
                 "segment", "industry", "signal_clause", "why_now", "signal_evidence",
                 "signal_kind", "signal_observed", "signal_source_url", "suppression"]  # fmt: skip
    files["lists/lint.csv"] = _csv(
        lint_cols,
        [
            {**a, "signal_kind": "event", "suppression": "unsubscribed" if i == 3 else ""}
            for i, a in enumerate(rows)
        ],
    )
    touch = (
        "**Step 1 — Day 0**\n\nSubject: `{{Company}} and its agents`\n\n"
        "> Hi {{First Name}},\n>\n> {{Why Now}} We help teams like {{Company}} record each agent action.\n"
        ">\n> Worth a short call?\n>\n> Sam\n"
    )
    for name, premise in (
        ("relay", "relay-premise"),
        ("seat", "seat-premise"),
        ("unknown", "no-such-premise"),
    ):
        files[f"lists/spec-{name}.md"] = f"Sign-off: Sam\npremise: {premise}\n\n{touch}".encode()
    items = [
        {
            "segment": a["segment"], "company": a["company"], "domain": a["company_domain"],
            "fit_score": int(a["score"]), "intent_feeds": ["feed-a"] if a["intent_feeds"] else [],
            "top_intent_score": int(a["top_intent_score"] or 0),
            "new_in_role": a["new_in_role"] == "true", "verdict": a["verdict"] if a["verdict"] in ("send", "re-angle", "drop") else "",
            "signal_observed": a.get("signal_observed", ""),
        }
        for a in rows
    ]  # fmt: skip
    files["lists/score-items.json"] = (json.dumps(items, indent=2, sort_keys=True) + "\n").encode()

    # The fixture's hook-matrix.md is generated by the code under test; it is not shipped here.
    return files


def write(out: Path = OUT) -> list[Path]:
    if out.exists():
        shutil.rmtree(out)  # the corpus is wholly generated; a stale file would outlive its builder
    written = []
    for rel, data in sorted(build(out).items()):
        path = out / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        written.append(path)
    return written


if __name__ == "__main__":
    paths = write()
    print(f"wrote {len(paths)} corpus files under {OUT}")
