"""Generate ``RENDER-STATE.md`` for a run folder from data — never from prose.

A handoff typed by hand under a context guard is where a film's overlays and sound design
fell out of the plan: the note listed the clips and the job ids, said nothing about the four
bubbles or nine cues the shot list declared, and the next session resumed from the note. This
CLI derives every line from the shot list, the render manifest, the sidecars on disk and the
coverage lint (``gtm_core.shots_coverage``, finish stage), so a field with no consumer cannot
be omitted by forgetting it.

    python -m gtm_core.render_state --shots <shots.json> --dir <run folder> [--ratio 9:16] [--out P]

Sections: a header (UTC time, shot list path); the per-shot status table; **Declared but
missing** (the coverage lint's finish-stage list); **Money** (the render manifest's cost fields,
or the refusal that it is unmetered); **What happens next**, one bullet per missing item naming
the exact verb that consumes it; and a trailer naming this generator. An existing file WITHOUT
that trailer is hand-written and is backed up to ``RENDER-STATE.hand-written.<ts>.md`` before
being overwritten — never deleted. Writes only inside ``--dir``.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from datetime import UTC, datetime
from pathlib import Path

from .shots_coverage import (
    CoverageReport,
    Finding,
    bed_declared,
    bed_present,
    caption_declared,
    captions_sidecar,
    check_coverage,
    cue_present,
    load_json,
    manifest_entry,
    overlay_burned,
    sfx_declared,
    shot_id_of,
)
from .shots_lint.overlay import overlay_entries

__all__ = ["GENERATOR_MARK", "NEXT_VERB", "render_state", "write_state", "main"]

GENERATOR_MARK = "Generated by gtm_core.render_state on"

#: The one verb that consumes each declared field. "What happens next" is this table applied to
#: the missing list, and nothing else — a bullet that is not derivable from a finding is prose.
NEXT_VERB: dict[str, str] = {
    "production.overlay": "video_finish overlays",
    "sfx": "gtm_core.audio_plan",
    "audio_bed": "gtm_core.audio_plan",
    "end_frame": "gtm_core.keyframe_request",
    "captions": "video_finish burn-captions",
}
_TAIL_VERBS = ("video_finish stitch", "video_finish run", "video_lint --manifest")


def _utc_now() -> datetime:
    return datetime.now(UTC)


def _yn(flag: bool) -> str:
    return "yes" if flag else "no"


def _job(entry: dict | None, *keys: str) -> str:
    for k in keys:
        v = (entry or {}).get(k)
        if v not in (None, "", "None"):
            return str(v)
    return "-"


def _clip_present(shot: dict, entry: dict | None, *, shots_path: Path, run_dir: Path) -> bool:
    raw = str(shot.get("file") or "").strip()
    if raw:
        p = Path(raw)
        return (p if p.is_absolute() else shots_path.parent / p).is_file()
    raw = str((entry or {}).get("path") or "").strip()
    return bool(raw) and (run_dir / raw).is_file()


def _shot_row(
    shot: dict, i: int, *, shots_path: Path, run_dir: Path, render, finish, cues
) -> list[str]:
    sid = shot_id_of(shot, i)
    n = str(shot.get("n") or i + 1)
    entry = manifest_entry(render, n)
    sfx_dir = run_dir / "sfx"
    overlay = "burned" if overlay_burned(run_dir, sid, finish) else "declared, NOT burned"
    sfx = "cue present" if cue_present(cues, sid, sfx_dir) else "declared, NO cue"
    bed = "bed present" if bed_present(cues, sfx_dir) else "declared, NO bed"
    return [
        n,
        f"{shot.get('duration_s', '-')}s",
        str(shot.get("role") or "presenter"),
        _job(entry, "start_image_job_id"),
        _job(entry, "end_image_job_id", "end_media_id") if shot.get("end_frame") else "-",
        _job(entry, "video_job_id"),
        _yn(_clip_present(shot, entry, shots_path=shots_path, run_dir=run_dir)),
        _yn(captions_sidecar(run_dir, sid).is_file()) if caption_declared(shot) else "-",
        overlay if overlay_entries(shot) else "-",
        sfx if sfx_declared(shot) else "-",
        bed if bed_declared(shot) else "-",
    ]


_COLUMNS = (
    "n", "dur", "role", "start still job", "end frame job", "video job", "clip on disk",
    "captions sidecar", "overlay", "sfx", "audio_bed",
)  # fmt: skip


def _table(rows: list[list[str]]) -> list[str]:
    head = "| " + " | ".join(_COLUMNS) + " |"
    rule = "|" + "|".join("---" for _ in _COLUMNS) + "|"
    return [head, rule] + ["| " + " | ".join(r) + " |" for r in rows]


def _money(render: dict | None) -> list[str]:
    if render and render.get("cost_source"):
        return [
            f"- cost_credits: {render.get('cost_credits')}",
            f"- cost_source: {render.get('cost_source')}",
            f"- cost_ledger_ts: {render.get('cost_ledger_ts') or '-'}",
        ]
    return ["- unmetered — refuse to write the manifest until metered"]


def _next(report: CoverageReport) -> list[str]:
    if not report.missing:
        return [
            "- nothing declared is missing — next: " + " → ".join(f"`{v}`" for v in _TAIL_VERBS)
        ]
    return [
        f"- `{NEXT_VERB.get(f.field, 'gtm_core.shots_coverage')}` — {f.shot_id} {f.field}: {f.detail}"
        for f in report.missing
    ]


def _missing(findings: tuple[Finding, ...]) -> list[str]:
    if not findings:
        return ["- none"]
    return [f"- {f.shot_id} `{f.field}` → {f.consumer}: {f.detail}" for f in findings]


def render_state(
    doc: dict, *, shots_path: Path, run_dir: Path, ratio: str = "9:16", now: datetime | None = None
) -> str:
    """The Markdown text — pure, so a test can assert on it without touching disk."""
    ts = (now or _utc_now()).strftime("%Y-%m-%dT%H:%M:%SZ")
    slug = ratio.replace(":", "x")
    render = load_json(run_dir / f"render-{slug}.json")
    finish = load_json(run_dir / f"finish-{slug}.json")
    cues = load_json(run_dir / "sfx" / "cues.json")
    shots = [s for s in doc.get("shots", []) if isinstance(s, dict)]
    report = check_coverage(doc, run_dir=run_dir, stage="finish", ratio=ratio)

    rows = [
        _shot_row(
            s, i, shots_path=shots_path, run_dir=run_dir, render=render, finish=finish, cues=cues
        )
        for i, s in enumerate(shots)
    ]
    lines = [
        "# RENDER-STATE",
        "",
        f"- generated: {ts}",
        f"- shot list: `{shots_path}`",
        f"- run folder: `{run_dir}`",
        f"- ratio: {ratio}",
        "",
        "## Per-shot status",
        "",
        *_table(rows),
        "",
        "## Declared but missing",
        "",
        *_missing(report.missing),
        "",
        "## Money",
        "",
        *_money(render),
        "",
        "## What happens next",
        "",
        *_next(report),
        "",
        f"{GENERATOR_MARK} {ts}; do not edit by hand.",
        "",
    ]
    return "\n".join(lines)


def write_state(
    doc: dict, *, shots_path: Path, run_dir: Path, out: Path | None = None, ratio: str = "9:16"
) -> tuple[Path, Path | None]:
    """Write the file; returns ``(written, backup)``. Refuses an ``out`` outside ``run_dir``."""
    now = _utc_now()
    target = (out or run_dir / "RENDER-STATE.md").resolve()
    root = run_dir.resolve()
    if root != target and root not in target.parents:
        raise ValueError(
            f"--out {target} is outside --dir {root}; this CLI writes only inside the run folder"
        )

    backup: Path | None = None
    if target.is_file() and GENERATOR_MARK not in target.read_text(encoding="utf-8"):
        # A file without the trailer was typed by a person. It is evidence of what they thought
        # the state was — kept beside the generated one, never overwritten and never deleted.
        backup = target.with_name(f"{target.stem}.hand-written.{now.strftime('%Y%m%dT%H%M%SZ')}.md")
        shutil.copy2(target, backup)

    text = render_state(doc, shots_path=shots_path, run_dir=run_dir, ratio=ratio, now=now)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    return target, backup


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="uv run python -m gtm_core.render_state")
    parser.add_argument("--shots", required=True, type=Path)
    parser.add_argument("--dir", required=True, type=Path, help="the run folder")
    parser.add_argument("--ratio", default="9:16")
    parser.add_argument("--out", type=Path, default=None, help="default <dir>/RENDER-STATE.md")
    args = parser.parse_args(argv)

    try:
        doc = json.loads(args.shots.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"[render-state] cannot read {args.shots}: {exc}", file=sys.stderr)
        return 1
    if not isinstance(doc, dict) or not isinstance(doc.get("shots"), list):
        print(f"[render-state] {args.shots} is not a shot list", file=sys.stderr)
        return 1
    if not args.dir.is_dir():
        print(f"[render-state] --dir {args.dir} is not a directory", file=sys.stderr)
        return 1
    try:
        written, backup = write_state(
            doc, shots_path=args.shots, run_dir=args.dir, out=args.out, ratio=args.ratio
        )
    except ValueError as exc:
        print(f"[render-state] {exc}", file=sys.stderr)
        return 2
    if backup:
        print(f"[render-state] hand-written file kept at {backup}")
    print(f"[render-state] wrote {written}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
