"""Agent-facing MCP task surface (Fleet Executor PRD §3 G9).

Exposes the companion PRD's executor verbs as MCP tools:
  - describe  — enumerate available packs or describe a specific pack
  - dispatch  — queue a pack-mode run (with inputs, context, external_ref)
  - status    — check current status and details of a run
  - artifacts — list file deliverables generated by a run
  - cost      — get cost and token breakdown for a run (or agent rollup)

Invariants:
  - Admitted by the SAME service layer and G0 rules as REST (CallerVerifier,
    AgentsTableRegistry, require_pack_mode, authorize_run_read).
  - No gate tool. Approval is unrepresentable on this surface (G4).
  - Header auth ONLY on HTTP transports (streamable HTTP without Authorization
    header is refused, never resolved to MCP_API_KEY environment fallback).
  - MCP_API_KEY environment fallback is allowed only for stdio / local transport.
  - Per-principal rate limits enforced (enforce_principal_rate).
  - No new egress path (§R6) — all calls invoke the Python service layer in-process.
"""

from __future__ import annotations

import logging
import os
import re
import uuid
from pathlib import Path
from typing import Any

from mcp.server.fastmcp import Context

from backend.callers.defaults import AgentsTableRegistry, ApiKeyServiceVerifier, JwtUserVerifier
from backend.callers.dependency import admit_all, authorize_run_read, verify_chain
from backend.callers.limits import enforce_agent_daily_cap, enforce_principal_rate
from backend.callers.ports import Refusal
from backend.callers.principal import Principal
from backend.database import workspace_scope
from backend.pack_catalog import descriptor, list_variants, variant_readiness
from backend.schemas import RunRequest
from backend.services.runs.admission import (
    find_existing_run_id,
    insert_run_row,
    resolve_acting_agent,
    resolve_pack_for_run,
)
from backend.services.runs.budget import admits
from backend.services.runs.principal_admission import (
    admit_run_creation,
    read_scope_for_principal,
)
from backend.services.runs.queries import (
    fetch_run_artifacts,
    fetch_run_detail,
)
from gtm_core.paths import workspace_profiles_root

log = logging.getLogger(__name__)

_UUID_REGEX = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", re.IGNORECASE
)


async def require_task_principal(ctx: Context | None, pool: Any) -> Principal:
    """Extract and validate caller identity for MCP task tools.

    Enforces header-only auth on HTTP transports and stdio fallback to MCP_API_KEY.
    """
    if pool is None:
        raise ValueError("Database pool unavailable — MCP server is still starting")

    raw = ""
    is_http = False
    try:
        if ctx is not None and getattr(ctx, "request_context", None) is not None:
            request = getattr(ctx.request_context, "request", None)
            if request is not None:
                is_http = True
                auth = request.headers.get("authorization", "")
                raw = re.sub(r"^[Bb]earer\s+", "", auth).strip()
    except (ValueError, AttributeError):
        raw = ""

    if is_http and not raw:
        raise ValueError("Missing Authorization header — header auth required on HTTP")

    if not raw and not is_http:
        raw = os.getenv("MCP_API_KEY", "")

    if not raw:
        raise ValueError("Missing API key — set Authorization: Bearer <key> header")

    try:
        principal = await verify_chain(raw, pool, [JwtUserVerifier(), ApiKeyServiceVerifier()])
        if principal.agent_id is not None:
            async with workspace_scope(pool, principal.workspace_id) as conn:
                await admit_all(principal, [AgentsTableRegistry()], conn)
        enforce_principal_rate(principal)
    except Refusal as exc:
        raise ValueError(f"{exc.code}: {exc.message or exc.code}") from exc

    return principal


async def describe_task(
    pack: str | None = None,
    ctx: Context | None = None,
    *,
    pool: Any,
    cfg: Any = None,
) -> dict:
    principal = await require_task_principal(ctx, pool)
    ws = principal.workspace_id
    agent_packs: list[str] | None = None
    profile_name: str | None = None

    if principal.agent_id is not None:
        async with workspace_scope(pool, ws) as conn:
            row = await conn.fetchrow(
                "SELECT profile_name, packs FROM agents WHERE id = $1::uuid AND workspace_id = $2::uuid",
                principal.agent_id,
                ws,
            )
        if row is None:
            raise ValueError("agent_not_found: Unknown agent")
        profile_name = row["profile_name"]
        agent_packs = list(row["packs"]) if row["packs"] is not None else None
    else:
        async with workspace_scope(pool, ws) as conn:
            row = await conn.fetchrow(
                "SELECT profile_name FROM profiles WHERE workspace_id = $1::uuid AND is_default = true",
                ws,
            )
        profile_name = row["profile_name"] if row else None

    if profile_name is None:
        return {"packs": []}

    repo_root = (
        getattr(cfg, "repo_root", None)
        or Path(os.environ.get("GTM_REPO_ROOT", Path.cwd())).resolve()
    )
    profiles_root = workspace_profiles_root(ws, repo_root)

    descriptors: list[dict] = []
    for resolved in list_variants(repo_root, profiles_root, profile_name):
        if agent_packs is not None and resolved.graph.pack not in agent_packs:
            continue
        if pack is not None and resolved.graph.pack != pack:
            continue
        try:
            report = variant_readiness(profiles_root, profile_name, resolved)
        except ValueError:
            report = None
        d = descriptor(resolved, entitlement=principal.entitlement, readiness=report)
        descriptors.append(d)

    if pack is not None:
        if not descriptors:
            raise ValueError(f"pack_not_found: Pack {pack!r} not found or not available")
        return {"pack": pack, "variants": descriptors}

    return {"packs": descriptors}


async def dispatch_task(
    pack: str,
    variant: str = "default",
    inputs: dict | None = None,
    context: dict | None = None,
    external_ref: str | None = None,
    client_request_id: str | None = None,
    ctx: Context | None = None,
    *,
    pool: Any,
    cfg: Any = None,
) -> dict:
    """Queue a pack-mode run with optional inputs, context, and external correlation ID."""
    principal = await require_task_principal(ctx, pool)
    repo_root = (
        getattr(cfg, "repo_root", None)
        or Path(os.environ.get("GTM_REPO_ROOT", Path.cwd())).resolve()
    )

    ws = principal.workspace_id
    body = RunRequest(
        pack=pack,
        variant=variant,
        inputs=inputs or {},
        context=context,
        external_ref=external_ref,
        client_request_id=client_request_id,
        agent_id=principal.agent_id if principal.kind == "service" else None,
    )

    # Idempotent replay fast-path
    if body.client_request_id is not None:
        existing_id = await find_existing_run_id(pool, ws, body.client_request_id)
        if existing_id is not None:
            detail = await fetch_run_detail(pool, ws, existing_id)
            if detail is not None:
                read_scope = await read_scope_for_principal(pool, ws, principal)
                authorize_run_read(principal, detail.get("agent_id"), read_scope)
                return detail

    try:
        admit_run_creation(principal, body)
    except Refusal as exc:
        raise ValueError(f"{exc.code}: {exc.message or exc.code}") from exc

    try:
        agent_row, profile_name = await resolve_acting_agent(pool, ws, body)
        await resolve_pack_for_run(
            repo_root,
            ws,
            principal.entitlement,
            profile_name,
            agent_row,
            body,
        )
    except Refusal as exc:
        raise ValueError(f"{exc.code}: {exc.message or exc.code}") from exc
    except Exception as exc:
        if hasattr(exc, "detail") and isinstance(exc.detail, dict):
            code = exc.detail.get("code", "dispatch_rejected")
            msg = exc.detail.get("message", code)
            raise ValueError(f"{code}: {msg}") from exc
        raise ValueError(str(exc)) from exc

    # Budget check
    agent_id = agent_row["agent_id"] if agent_row is not None else None
    agent_budget_usd = (
        float(agent_row["monthly_budget_usd"])
        if agent_row is not None and agent_row["monthly_budget_usd"] is not None
        else None
    )
    if not await admits(pool, ws, agent_id, agent_budget_usd):
        raise ValueError("cost_cap_reached: monthly cost cap reached")

    # Enforce agent daily cap
    try:
        await enforce_agent_daily_cap(pool, cfg, principal, agent_row, "mcp/dispatch")
    except Refusal as exc:
        raise ValueError(f"{exc.code}: {exc.message or exc.code}") from exc

    run_id = str(uuid.uuid4())
    (
        effective_run_id,
        existed,
        run_agent_id,
        _agent_budget_usd,
        _run_language,
    ) = await insert_run_row(
        pool,
        ws,
        run_id,
        prompt="",
        is_pack=True,
        agent_row=agent_row,
        body=body,
    )

    return {
        "run_id": effective_run_id,
        "status": "queued",
        "pack": pack,
        "variant": variant,
        "external_ref": external_ref,
    }


async def status_task(
    run_id: str,
    ctx: Context | None = None,
    *,
    pool: Any,
    cfg: Any = None,
) -> dict:
    """Fetch status and current state of a run."""
    principal = await require_task_principal(ctx, pool)
    if not _UUID_REGEX.match(run_id):
        raise ValueError("invalid_run_id: run_id must be a valid UUID")

    ws = principal.workspace_id
    detail = await fetch_run_detail(pool, ws, run_id)
    if detail is None:
        raise ValueError("run_not_found: Run not found")

    read_scope = await read_scope_for_principal(pool, ws, principal)
    try:
        authorize_run_read(principal, detail.get("agent_id"), read_scope)
    except Refusal as exc:
        raise ValueError(f"{exc.code}: {exc.message or exc.code}") from exc

    return detail


async def artifacts_task(
    run_id: str,
    ctx: Context | None = None,
    *,
    pool: Any,
    cfg: Any = None,
) -> dict:
    """List file deliverables generated by a run."""
    principal = await require_task_principal(ctx, pool)
    if not _UUID_REGEX.match(run_id):
        raise ValueError("invalid_run_id: run_id must be a valid UUID")

    ws = principal.workspace_id
    detail = await fetch_run_detail(pool, ws, run_id)
    if detail is None:
        raise ValueError("run_not_found: Run not found")

    read_scope = await read_scope_for_principal(pool, ws, principal)
    try:
        authorize_run_read(principal, detail.get("agent_id"), read_scope)
    except Refusal as exc:
        raise ValueError(f"{exc.code}: {exc.message or exc.code}") from exc

    artifacts = await fetch_run_artifacts(pool, ws, run_id)
    return {"run_id": run_id, "artifacts": artifacts or []}


async def cost_task(
    run_id: str | None = None,
    ctx: Context | None = None,
    *,
    pool: Any,
    cfg: Any = None,
) -> dict:
    """Get cost and token usage breakdown for a specific run or caller rollup."""
    principal = await require_task_principal(ctx, pool)
    ws = principal.workspace_id

    if run_id is not None:
        if not _UUID_REGEX.match(run_id):
            raise ValueError("invalid_run_id: run_id must be a valid UUID")

        detail = await fetch_run_detail(pool, ws, run_id)
        if detail is None:
            raise ValueError("run_not_found: Run not found")

        read_scope = await read_scope_for_principal(pool, ws, principal)
        try:
            authorize_run_read(principal, detail.get("agent_id"), read_scope)
        except Refusal as exc:
            raise ValueError(f"{exc.code}: {exc.message or exc.code}") from exc

        async with workspace_scope(pool, ws) as conn:
            rows = await conn.fetch(
                """SELECT stage,
                          model,
                          COUNT(*)                    AS calls,
                          SUM(cost_usd)::float        AS cost_usd,
                          COALESCE(SUM(input_tokens), 0)  AS input_tokens,
                          COALESCE(SUM(output_tokens), 0) AS output_tokens
                   FROM cost_records
                   WHERE workspace_id = $1::uuid AND run_id = $2
                   GROUP BY stage, model
                   ORDER BY cost_usd DESC""",
                ws,
                run_id,
            )
        total = sum(r["cost_usd"] for r in rows)
        return {
            "run_id": run_id,
            "total_usd": round(total, 6),
            "breakdown": [dict(r) for r in rows],
        }

    # Rollup across the principal's scope
    read_scope = await read_scope_for_principal(pool, ws, principal)
    async with workspace_scope(pool, ws) as conn:
        if principal.kind == "service" and read_scope != "workspace":
            rows = await conn.fetch(
                """SELECT stage,
                          model,
                          COUNT(*)                    AS calls,
                          SUM(cost_usd)::float        AS cost_usd,
                          COALESCE(SUM(input_tokens), 0)  AS input_tokens,
                          COALESCE(SUM(output_tokens), 0) AS output_tokens
                   FROM cost_records
                   WHERE workspace_id = $1::uuid AND agent_id = $2::uuid
                   GROUP BY stage, model
                   ORDER BY cost_usd DESC""",
                ws,
                principal.agent_id,
            )
        else:
            rows = await conn.fetch(
                """SELECT stage,
                          model,
                          COUNT(*)                    AS calls,
                          SUM(cost_usd)::float        AS cost_usd,
                          COALESCE(SUM(input_tokens), 0)  AS input_tokens,
                          COALESCE(SUM(output_tokens), 0) AS output_tokens
                   FROM cost_records
                   WHERE workspace_id = $1::uuid
                   GROUP BY stage, model
                   ORDER BY cost_usd DESC""",
                ws,
            )
    total = sum(r["cost_usd"] for r in rows)
    return {
        "run_id": None,
        "total_usd": round(total, 6),
        "breakdown": [dict(r) for r in rows],
    }
