#!/usr/bin/env python3
"""Shared plumbing for the linter tripwire corpus — see tests/tripwire/README.md.

Two kinds of golden live next to this file and are regenerated by ONE command::

    uv run python tests/tripwire/support.py --write

* ``help/<linter>.help.txt`` — the byte-exact ``python -m gtm_core.<linter> --help`` text.
* ``cli/<case>.stdout.txt`` — the byte-exact stdout of one committed CLI invocation (``CASES``).

Regenerate only after a DELIBERATE CLI change, never to turn a red run green: a golden that
drifts during a pure-motion split is the drift the corpus exists to catch (PRD §6.1 row 7).
"""

from __future__ import annotations

import difflib
import json
import os
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]
HELP_DIR = HERE / "help"
CLI_DIR = HERE / "cli"
LINTERS = ("deck_lint", "brief_lint", "video_lint", "shots_lint", "content_quality")
REGENERATE = "regenerate with `uv run python tests/tripwire/support.py --write`"

#: A fabricated ffprobe payload: the 2026-08-15 defect shape (720x1280 @ 25fps, audio present).
PROBE_LOW = {
    "streams": [
        {
            "codec_type": "video",
            "width": 720,
            "height": 1280,
            "r_frame_rate": "25/1",
            "bit_rate": "3000000",
            "pix_fmt": "yuv420p",
        },
        {"codec_type": "audio", "bit_rate": "128000"},
    ],
    "format": {"duration": "15.500000", "bit_rate": "3128000"},
}

#: A fabricated ffprobe payload for an asset that clears every delivery floor.
PROBE_OK = {
    "streams": [
        {
            "codec_type": "video",
            "width": 1080,
            "height": 1920,
            "r_frame_rate": "30/1",
            "bit_rate": "8000000",
            "pix_fmt": "yuv420p",
        },
        {"codec_type": "audio", "bit_rate": "128000"},
    ],
    "format": {"duration": "12.000000", "bit_rate": "8128000"},
}


@dataclass(frozen=True)
class CliCase:
    """One committed CLI invocation whose stdout is pinned byte-for-byte."""

    name: str
    module: str
    args: tuple[str, ...]
    cwd: str  # relative to tests/tripwire — paths in the args stay relative, so stdout is portable
    exit_code: int
    #: env var -> path relative to tests/tripwire (made absolute at run time; never echoed)
    env_paths: dict[str, str] = field(default_factory=dict)
    #: when set, a fake ``ffprobe`` printing this payload is put first on PATH
    ffprobe: dict | None = None


_CQ_ENV = {
    "GTM_PROFILES_ROOT": "content_quality/profiles-root",
    "GTM_SAFE_SHARE_DENYLIST_FILE": "content_quality/safe-share-denylist.txt",
}


def _cq(name: str, cmd: str, profile: str, item: str, exit_code: int, **kw) -> CliCase:
    args = ("--content-root", "content-root", cmd, "--profile", profile, "--item", item)
    return CliCase(name, "content_quality", args, "content_quality", exit_code, _CQ_ENV, **kw)


CASES: dict[str, tuple[CliCase, ...]] = {
    "deck_lint": (
        CliCase(
            "deck-clean",
            "deck_lint",
            ("clean.slides.md", "--dossier", "dossier.json", "--inputs", "inputs"),
            "deck_lint",
            0,
        ),
        CliCase(
            "deck-dirty-report",
            "deck_lint",
            ("dirty.slides.md", "--minutes", "20", "--theme", "theme-bad"),
            "deck_lint",
            1,
        ),
        CliCase(
            "deck-claims-json",
            "deck_lint",
            ("claims.slides.md", "--dossier", "dossier.json", "--inputs", "inputs", "--json"),
            "deck_lint",
            1,
        ),
    ),
    "brief_lint": (
        CliCase("brief-clean", "brief_lint", ("clean.html",), "brief_lint", 0),
        CliCase(
            "brief-report",
            "brief_lint",
            ("jargon.html", "structure.html", "record.md"),
            "brief_lint",
            1,
        ),
        CliCase("brief-json", "brief_lint", ("sections.html", "--json"), "brief_lint", 1),
    ),
    "video_lint": (
        CliCase(
            "video-report",
            "video_lint",
            ("asset.mp4", "--ratio", "9:16", "--fast", "--manifest", "cli-manifest.json"),
            "video_lint",
            1,
            ffprobe=PROBE_LOW,
        ),
        CliCase(
            "video-json-predictor",
            "video_lint",
            (
                "asset.mp4",
                "--ratio",
                "9:16",
                "--fast",
                "--manifest",
                "cli-manifest.json",
                "--purpose",
                "predictor",
                "--json",
            ),
            "video_lint",
            1,
            ffprobe=PROBE_LOW,
        ),
    ),
    "shots_lint": (
        CliCase("shots-rules", "shots_lint", ("--rules",), "shots_lint", 0),
        CliCase(
            "shots-bad",
            "shots_lint",
            ("shots-bad.shots.json", "--voice-grade", "instant", "--voice-id", ""),
            "shots_lint",
            1,
        ),
        CliCase(
            "shots-clean",
            "shots_lint",
            ("clean.shots.json", "--voice-grade", "professional", "--voice-id", "voice-1"),
            "shots_lint",
            0,
        ),
    ),
    "content_quality": (
        _cq("cq-pre-clean", "pre", "acme", "text-clean", 0),
        _cq("cq-pre-bad", "pre", "acme", "text-bad", 1),
        _cq("cq-script-overcount", "script", "acme", "script-overcount", 1),
        _cq("cq-register-recited", "register", "acme", "script-recited", 0),
        _cq("cq-post-text-bad", "post", "acme", "text-bad", 1),
        _cq("cq-post-reel-lowres", "post", "acme", "reel-lowres", 1, ffprobe=PROBE_LOW),
    ),
}


def fake_ffprobe(bin_dir: Path, payload: dict) -> Path:
    """Write an executable ``ffprobe`` that prints ``payload`` whatever it is asked.

    ``gtm_core.video_lint.probe`` resolves the binary with ``shutil.which``, so putting this
    directory first on PATH exercises the real probe → ``Probe.from_ffprobe_json`` path with no
    media and no ffmpeg on the machine.
    """
    bin_dir.mkdir(parents=True, exist_ok=True)
    script = bin_dir / "ffprobe"
    script.write_text(
        "#!/bin/sh\ncat <<'GTM_TRIPWIRE_JSON'\n" + json.dumps(payload) + "\nGTM_TRIPWIRE_JSON\n",
        encoding="utf-8",
    )
    script.chmod(0o755)
    return bin_dir


def path_with(bin_dir: Path) -> str:
    return f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}"


def run_module(
    module: str, args: tuple[str, ...], *, cwd: Path, env: dict[str, str] | None = None
) -> subprocess.CompletedProcess[str]:
    """``python -m gtm_core.<module> ...`` under a fixed terminal width and encoding."""
    full_env = {
        **os.environ,
        "COLUMNS": "80",
        "PYTHONIOENCODING": "utf-8",
        "PYTHONPATH": str(REPO_ROOT),
    }
    full_env.update(env or {})
    return subprocess.run(  # nosec B603 — argv list, our own interpreter, no shell
        [sys.executable, "-m", f"gtm_core.{module}", *args],
        cwd=str(cwd),
        env=full_env,
        capture_output=True,
        text=True,
        encoding="utf-8",
        timeout=300,
        check=False,
    )


#: Assets the CQ manifests point at. Only existence matters — every probe in this corpus is
#: the fake `ffprobe` above — so they are CREATED here rather than committed: a real .mp4 is
#: matched by .gitignore's `*.mp4` and would be present locally and absent on CI, which is
#: exactly how `cq-post-reel-lowres` passed here and failed there.
_PLACEHOLDER_ASSETS = (HERE / "content_quality" / "assets" / "probe-only.mp4",)


def ensure_placeholder_assets() -> None:
    for path in _PLACEHOLDER_ASSETS:
        if not path.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(b"\x00" * 104)  # never decoded; ffprobe is faked


def run_case(case: CliCase, scratch: Path) -> subprocess.CompletedProcess[str]:
    ensure_placeholder_assets()
    env = {var: str(HERE / rel) for var, rel in case.env_paths.items()}
    if case.ffprobe is not None:
        env["PATH"] = path_with(fake_ffprobe(scratch / "bin", case.ffprobe))
    return run_module(case.module, case.args, cwd=HERE / case.cwd, env=env)


def help_golden(module: str) -> Path:
    return HELP_DIR / f"{module}.help.txt"


def stdout_golden(case: CliCase) -> Path:
    return CLI_DIR / f"{case.name}.stdout.txt"


def check_help(module: str) -> None:
    proc = run_module(module, ("--help",), cwd=REPO_ROOT)
    assert proc.returncode == 0, proc.stderr
    _compare(help_golden(module), proc.stdout)


def check_case(case: CliCase, scratch: Path) -> None:
    """Exit code + byte-exact stdout, and determinism proven by running twice."""
    first = run_case(case, scratch / "run1")
    second = run_case(case, scratch / "run2")
    assert first.stdout == second.stdout, f"{case.name}: stdout differs between two runs"
    assert first.returncode == case.exit_code, (
        f"{case.name}: exit {first.returncode} != {case.exit_code}\n"
        f"stdout:\n{first.stdout}\nstderr:\n{first.stderr}"
    )
    _compare(stdout_golden(case), first.stdout)


def _compare(golden: Path, actual: str) -> None:
    assert golden.is_file(), f"missing golden {golden.name} — {REGENERATE}"
    expected = golden.read_text(encoding="utf-8")
    if actual == expected:
        return
    diff = "".join(
        difflib.unified_diff(
            expected.splitlines(True), actual.splitlines(True), "golden", "actual", n=2
        )
    )
    raise AssertionError(
        f"{golden.name} drifted — a pure-motion split must not change CLI output; "
        f"if the change is deliberate, {REGENERATE}\n{diff[:4000]}"
    )


def write_goldens() -> None:
    HELP_DIR.mkdir(exist_ok=True)
    CLI_DIR.mkdir(exist_ok=True)
    for module in LINTERS:
        proc = run_module(module, ("--help",), cwd=REPO_ROOT)
        if proc.returncode != 0:
            raise SystemExit(f"{module} --help failed:\n{proc.stderr}")
        help_golden(module).write_text(proc.stdout, encoding="utf-8")
        print(f"wrote {help_golden(module).relative_to(REPO_ROOT)}")
    with tempfile.TemporaryDirectory() as tmp:
        for cases in CASES.values():
            for case in cases:
                proc = run_case(case, Path(tmp) / case.name)
                if proc.returncode != case.exit_code:
                    raise SystemExit(
                        f"{case.name}: exit {proc.returncode} != {case.exit_code}\n{proc.stderr}"
                    )
                stdout_golden(case).write_text(proc.stdout, encoding="utf-8")
                print(f"wrote {stdout_golden(case).relative_to(REPO_ROOT)}")


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if args != ["--write"]:
        print(__doc__)
        return 2
    write_goldens()
    return 0


if __name__ == "__main__":
    sys.exit(main())
