from __future__ import annotations


def _render_profile_md(
    company: dict,
    voice: dict,
    icp: dict,
    pillars: list,
    products: list,
    brand: dict,
    settings: dict | None = None,
) -> str:
    settings = settings or {}
    slug = company["slug"]
    brand_name = company["brand_name"]
    name = company["name"]
    social = company.get("social_handle", "")
    markets = company.get("markets", [])
    palette = brand.get("palette", [])

    title = settings.get("title", "Founder")
    email_signature = settings.get("email_signature", name.split()[0])
    segment_mix = settings.get("segment_mix", "70% startup / 30% enterprise")
    monthly_tool_budget_usd = settings.get("monthly_tool_budget_usd", 50)
    per_run_cap_usd = settings.get("per_run_cap_usd", 10)
    language = settings.get("language", "English")

    flagship = next((p for p in products if p.get("flagship")), products[0] if products else {})
    flagship_slug = flagship.get("slug", "") if flagship else ""

    products_yaml = "\n".join(
        f"  - {{ slug: {p['slug']}, name: {p['name']}, "
        f"capabilities: [{', '.join(p.get('capabilities', []))}], "
        f"flagship: {'true' if p.get('flagship') else 'false'} }}"
        for p in products
    )

    pillars_inline = "[" + ", ".join(pillars) + "]" if pillars else "[]"
    palette_inline = str(palette) if palette else '["#000000", "#FFFFFF"]'
    connectors_block = _render_connectors_block(settings.get("connectors", []))

    return f"""# {name} — Profile Bundle

> Active-profile config for the **{slug}** company bundle. Generated by profile-onboard.
> **Config only — never secrets.** API keys live in `.env`.

## Identity
```
name:            {name}
title:           {title}
email_signature: {email_signature}
```

## Company & products  *(company → many products; skills resolve by capability)*
```
company:         {name}
brand_name:      {brand_name}
default_product: {flagship_slug}
products:
{products_yaml}
```

## Voice style  *(full guide: knowledge/voice.md)*
```
voice_style: |
  {voice.get("tone", "")}
```

## Markets
```
target_markets:  {markets}
language:        {language}
```

## ICP weighting  *(prospect, call-prep, account-plan)*
```
segment_mix:         {segment_mix}
# Full ICP and persona cards: knowledge/icp-personas.md
```

## Budget
```
monthly_tool_budget_usd: {monthly_tool_budget_usd}
per_run_cap_usd:         {per_run_cap_usd}
```

## Connector plans & entitlements  *(which plan each metered tool is on, and what it allows)*

The dollar budget above governs metered-per-call tools (Vibe credits, generation calls). A
flat-subscription tool (RocketReach and similar) bills near-$0 per call, so its own real
constraint is a monthly count, not a dollar figure — capture that here so skills can pace against
it instead of only the budget above. Re-confirm plan/allowance whenever it changes.

{connectors_block}

## Output location
```
output_folder: content/{slug}/
```
> Per-account deliverables go under `content/{slug}/accounts/ACCOUNT-SLUG/` (kebab-cased target company)

## Brand  *(carousel-visuals, build-deck, deck rendering)*
```
brand_palette:   {palette_inline}
brand_assets:    knowledge/brand/
# See knowledge/brand-notes.md for full brand guidance
```

## Content OS  *(content-radar / -plan / -studio)*
```
content_pillars: {pillars_inline}
social_handle:   {social}
```
"""


def _render_connectors_block(connectors: list) -> str:
    """Render the 'Connector plans & entitlements' body from settings.connectors[].

    Each entry captures a metered tool's real plan/allowance/features — distinct from the
    dollar budget above, since a flat-subscription tool (RocketReach and similar) bills near-$0
    per call and needs a count-based limit to pace against instead. No angle-bracket
    placeholders when empty (see test_no_angle_bracket_placeholders_ship) — plain-English
    guidance instead, matching every other data-derived section in this file.
    """
    if not connectors:
        return (
            "```\n"
            "# No connector plans captured yet. When a metered tool is connected (Vibe Prospecting,\n"
            "# RocketReach, Firecrawl, ...), add its plan name, monthly allowance, and enabled premium\n"
            "# features here — see profiles/_template/PROFILE.md for the shape.\n"
            "```"
        )
    lines = ["```"]
    for c in connectors:
        name = c.get("name", "unknown")
        allowance = c.get("monthly_allowance") or {}
        allowance_str = (
            f"{allowance.get('limit')} {allowance.get('unit')}/mo"
            if allowance.get("limit") is not None and allowance.get("unit")
            else "not captured"
        )
        features = c.get("features", [])
        features_str = "[" + ", ".join(features) + "]" if features else "[]"

        lines.append(f"{name}:")
        lines.append(f"  plan:              {c.get('plan', 'not captured')}")
        lines.append(f"  billing:           {c.get('billing', 'not captured')}")
        lines.append(f"  monthly_allowance: {allowance_str}")
        lines.append(f"  features:          {features_str}")
        if c.get("notes"):
            lines.append(f"  notes:             {c['notes']}")
    lines.append("```")
    return "\n".join(lines)


def _render_voice_md(voice: dict) -> str:
    principles = "\n".join(f"- {p}" for p in voice.get("principles", []))
    ban_list = "\n".join(f"- {b}" for b in voice.get("ban_list", []))
    examples = "\n\n".join(f"> {e}" for e in voice.get("examples", []))

    return f"""# Voice & Tone Guide

## Tone
{voice.get("tone", "")}

## Principles
{principles}

## Ban list
Words and phrases to avoid:

{ban_list}

## Examples of the voice in action
{examples if examples else "_No examples captured. Add verbatim quotes from company copy._"}
"""


def _render_company_md(company: dict, draft: dict) -> str:
    return f"""# Company Overview

**Name:** {company["name"]}
**Brand:** {company["brand_name"]}
**Description:** {company["description"]}
**Markets:** {", ".join(company.get("markets", []))}
**Social:** {company.get("social_handle", "")}

## Confidence: {draft.get("confidence", "unknown")}

## Gaps identified
{chr(10).join("- " + g for g in draft.get("gaps", [])) or "_None_"}
"""


def _render_brand_notes_md(brand: dict) -> str:
    palette = brand.get("palette", [])
    palette_list = "\n".join(f"- `{c}`" for c in palette) if palette else "_Not captured._"
    assets_note = brand.get("assets_note", "_No assets note captured from source._")

    return f"""# Brand Notes

> Generated by profile-onboard. Review and update from the company's brand guide.

## Colour palette
{palette_list}

## Assets
{assets_note}

## Next steps
- Add official brand assets to `knowledge/brand/`
- Add logos (SVG, PNG) and any brand deck template
- Update brand_palette in PROFILE.md with confirmed hex codes
"""


def _render_market_scan_config_md(products: list) -> str:
    all_refs: list[str] = []
    for product in products:
        for ref in product.get("references", []):
            url = ref.get("url", "")
            title = ref.get("title", url)
            summary = ref.get("summary", "")
            all_refs.append(f"- [{title}]({url}){': ' + summary if summary else ''}")
    refs_text = "\n".join(all_refs) if all_refs else "_No references captured._"

    return f"""# Market Scan Config

## Reference sources
{refs_text}

## Scan instructions
Use the above URLs as seed sources for market and competitor research.
"""
